// Generated by scripts/build-history.ts; do not edit.
export const HISTORY_FILES = {
  "main": {
    "path": "history/history.44de8c50.json",
    "sha256": "44de8c50412c292325f36b051898afadf0b7bf6ef70647f4a97be613db06a179"
  },
  "municipalities": {
    "AC": {
      "path": "history/history-mun-ac.1d970bdb.json",
      "sha256": "1d970bdbb85291067fa11aa495cdf86e81d0200444d1ce38c9675c94875fdde0"
    },
    "AL": {
      "path": "history/history-mun-al.23c6b167.json",
      "sha256": "23c6b16703ab06d060bd64b6736456f97812c551e84d795209c6b21bce64bc3c"
    },
    "AM": {
      "path": "history/history-mun-am.c7298450.json",
      "sha256": "c7298450e8376b7b7c5d00b6a99321931cc4d8d505c2bb1210486a679ebfdbc0"
    },
    "AP": {
      "path": "history/history-mun-ap.84757ca2.json",
      "sha256": "84757ca2cc529dc3b992ad97d20bbc38c7d4f335c623ea0f872b889a168fe0fa"
    },
    "BA": {
      "path": "history/history-mun-ba.2600fd39.json",
      "sha256": "2600fd39ab93e14fe845e0c80058a28f97057c44017f1abe15ffbbe7735ee995"
    },
    "CE": {
      "path": "history/history-mun-ce.fdad3057.json",
      "sha256": "fdad305752c0a43fc46aef91d5250a5fd20b81a169ebc221980b8cde3520f462"
    },
    "DF": {
      "path": "history/history-mun-df.33eb4a02.json",
      "sha256": "33eb4a028e80d45faf90c1cf1a852c62242af333d6f8815a209b64c3c72a0352"
    },
    "ES": {
      "path": "history/history-mun-es.e240b2bf.json",
      "sha256": "e240b2bf5caaf374febaefe8b164c8583ce69c2d46d61a926115ed83ff59dbe1"
    },
    "GO": {
      "path": "history/history-mun-go.c1a678d2.json",
      "sha256": "c1a678d2d6c0b10a01461b2535a8db24ee7055e0d0b9f37fbc8ed94ee099f743"
    },
    "MA": {
      "path": "history/history-mun-ma.3a62193c.json",
      "sha256": "3a62193ce56c988d4fe1034a780dde46e6bdc7932c226b2b75ed1456991da085"
    },
    "MG": {
      "path": "history/history-mun-mg.45e1b508.json",
      "sha256": "45e1b50829192ddceb4da8c073fe0b180f9802b5252f9233947c90e7e623f1ca"
    },
    "MS": {
      "path": "history/history-mun-ms.54e61485.json",
      "sha256": "54e61485a4c9103ed0ecdca0552c9a02f8b861ea02fbee5c7f16e50ef1fb2c62"
    },
    "MT": {
      "path": "history/history-mun-mt.f3ef3049.json",
      "sha256": "f3ef30498c7a242d5fd129acd508c0d74f7f434f754304bd81bfc110f60776a0"
    },
    "PA": {
      "path": "history/history-mun-pa.f9ac9622.json",
      "sha256": "f9ac96221f1ab76783fa9746d85d1267a0b84a5dd260abd6e235871c1a71e494"
    },
    "PB": {
      "path": "history/history-mun-pb.3c13d35b.json",
      "sha256": "3c13d35b23be3d9cb439507c418083e381f31ab75b15244ee6a645bf83356b13"
    },
    "PE": {
      "path": "history/history-mun-pe.4b705cf2.json",
      "sha256": "4b705cf2b5b1c276f7fe9a6121ed74347b5be3304210d743c9a226e7b34bd923"
    },
    "PI": {
      "path": "history/history-mun-pi.404ac28c.json",
      "sha256": "404ac28c4417a6f7bfa4f47198e1dfc017d19e6ff667180a5adf8fce746a80e6"
    },
    "PR": {
      "path": "history/history-mun-pr.bacf6ac0.json",
      "sha256": "bacf6ac07e1c78b9d114ab111929f410999fe8f2051e55f413ab28f4504f96ab"
    },
    "RJ": {
      "path": "history/history-mun-rj.ddac06fa.json",
      "sha256": "ddac06fa112929f90dd683ff0d7f9c26d595f9c904b529380008a89d0aad55d8"
    },
    "RN": {
      "path": "history/history-mun-rn.8d91f8b1.json",
      "sha256": "8d91f8b1cbb9bbdf864de63401d47f382435c23a37eed982dbd8da0666db4d36"
    },
    "RO": {
      "path": "history/history-mun-ro.a2a01146.json",
      "sha256": "a2a011469478b0b6f745abfd66d0b3daf35fabfa55b03903e9c5f9c0886aaca8"
    },
    "RR": {
      "path": "history/history-mun-rr.cbce08a4.json",
      "sha256": "cbce08a45a8e428d72653b0891be8ee41dc512c75b25a85c8d2d157b9025d836"
    },
    "RS": {
      "path": "history/history-mun-rs.9ca367ce.json",
      "sha256": "9ca367ce3a2bad9e63f8e74fb5c719d5bfd07202f269194349ff8c4e4756229c"
    },
    "SC": {
      "path": "history/history-mun-sc.92ab9f35.json",
      "sha256": "92ab9f359511d9b1e963008103df41428ce7174cbaeb6cc3c12330c5dd63df46"
    },
    "SE": {
      "path": "history/history-mun-se.b8ba981b.json",
      "sha256": "b8ba981bb8496e0d62294a11345c7ab1f2aad62f5bdaa4d58875159b5d8345c9"
    },
    "SP": {
      "path": "history/history-mun-sp.a4725512.json",
      "sha256": "a472551220d56179cad9618695b57190ab979b3ef30bf42ec8eaeb3d24ebbbc3"
    },
    "TO": {
      "path": "history/history-mun-to.017726d1.json",
      "sha256": "017726d19f99d78061546bfc07bf4e158f09cecc39505fc187095ecd2dac0dba"
    }
  }
} as const;
