// Generated by scripts/build-geometry.ts; do not edit.
export const GEO_FILE = {
  path: "geo/br-mun-2025.5e5c8c26.topo.json",
  sha256: "5e5c8c26c7c971b474e6e97cb844272fcf67a5aab09d227a16fd53366f8de192",
  index: "d0a3d601da8224f1e9303132c95b1ff73763ddc88ae10ff425d14ec60d3aad2c",
} as const;
